project:
  type: book

book:
  title: "ec1027-guide"
  author: "José C. Pernías"
  date: "6/26/2023"
  chapters:
    - index.qmd
    - part: cs-part.qmd
      chapters:
        - intro.qmd
    - part: ts-part.qmd
      chapters:
        - summary.qmd
    - references.qmd

lang: es

bibliography: references.bib

format:
  html:
    theme: litera

editor: visual

execute:
  freeze: auto
